name: Website Updates

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username":"Repo Updates",
            "embeds":[{
              "title":"1 New Commit",
              "description":"**${{ github.event.head_commit.message }}**",
              "color":3447003,
              "author":{
                "name":"${{ github.actor }}"
              },
              "footer":{
                "text":"${{ github.repository }}"
              }
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
