name: notify

on:
push:

jobs:
discord:
runs-on: ubuntu-latest

```
steps:
  - name: Send Discord Embed
    run: |
      curl \
        -H "Content-Type: application/json" \
        -X POST \
        -d "{\"embeds\":[{\"title\":\"Test\",\"description\":\"Hello Discord\",\"color\":3447003}]}" \
        "${{ secrets.DISCORD_WEBHOOK }}"
```
